table 'Latest Ferry Positions'
	lineageTag: 8483f6f2-5b16-415c-af03-6312433f888a

	measure Size = 10
		formatString: 0
		lineageTag: 22037ba9-070b-411a-bc3b-d3dd1b93c727

	measure 'Ferry Icon' = ```
			"data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQ4IiBoZWlnaHQ9IjI0OCIgeG1sbnM9Imh0dHA6Ly93d3cu" 
			```
		lineageTag: c01cf343-8f96-46b6-82e5-6b3275781f57

	measure 'Icon Tooltip' = ```
			
			"data:image/svg+xml;base64,PHN2ZyB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIg"
			
			```
		lineageTag: a0afd86d-fba8-47da-baf9-c5ac984d6610

	measure Logo = "data:image/svg+xml;base64,PHN2ZyB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIg"
		lineageTag: 1ad3b290-48bf-47d1-8943-11a75eebb82e

	column ferry_name
		dataType: string
		lineageTag: e9c47063-f32c-45fa-b2d2-7728cfb246f1
		summarizeBy: none
		sourceColumn: ferry_name

		annotation SummarizationSetBy = Automatic

	column ferry_lat
		dataType: double
		lineageTag: ce9302ec-51ae-4035-a73d-dbb946a88418
		summarizeBy: sum
		sourceColumn: ferry_lat

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ferry_long
		dataType: double
		lineageTag: c4b85413-1b3b-449a-9f68-0be1b7628e77
		summarizeBy: sum
		sourceColumn: ferry_long

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column timestamp
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetimeoffset
		lineageTag: 2a3a8ea1-252e-40eb-aa5c-dd2265e2cf0b
		summarizeBy: none
		sourceColumn: timestamp

		annotation SummarizationSetBy = Automatic

	column ferry_destination
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 30230c00-13bf-4f39-a712-3208b07f018c
		summarizeBy: none
		sourceColumn: ferry_destination

		annotation SummarizationSetBy = Automatic

	partition 'Latest Ferry Positions' = m
		mode: directQuery
		source =
				let
				Source = AzureDataExplorer.Contents("https://trd-1u2v2sxv19k32hbdcc.z4.kusto.fabric.microsoft.com", "SydneyFerriesKustoDB", "SydneyFerries
				| where timestamp > ago(2m)
				| summarize max_timestamp = max(timestamp) by ferry_name
				| join kind=inner (
				    SydneyFerries
				    | project ferry_name, ferry_lat, ferry_long, ferry_destination, timestamp
				) on ferry_name
				| where timestamp == max_timestamp
				| project ferry_name, ferry_lat, ferry_long,timestamp, ferry_destination", [])
				in
				    Source

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

